// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awiphzyrlorpexpfclze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aXBoenlybG9ycGV4cGZjbHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjAzMjIsImV4cCI6MjA2NDQzNjMyMn0.k6LRZCrTCqoo4RNInFGDKYfZnOhYUTINWghGJODkZoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);